apiVersion: v1
kind: Namespace
metadata:
  name: cust-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-tools-6
  namespace: cust-tools
spec:
  selector:
    matchLabels:
      app: cust-tools
  replicas: 3
  template:
    metadata:
      labels:
        app: cust-tools
    spec:
      containers:
        - name: cust-tools
          image: greghint/hello-app
          ports:
            - containerPort: 8080
